---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/s3-bucket
  type: udm.Application  
  children:
  - name: 1.0.0
    type: udm.DeploymentPackage
    deployables:
    - name: mybucket
      type: terraform.Module
      inputVariables:
        aws_region: '{{aws_region}}'        
        bucket_name: "demo-tfe-s3"
      workspaceName: demo-{{aws_region}}
      applyDestroyOperation: "true"
      file: !file "artifacts/1.0.0/bucket"
  
