---
apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: Applications/multi
    type: udm.Application
    lastVersion: 3.0.4
    children:
      - name: 2.0.1
        type: udm.DeploymentPackage
        deployables:
          - name: s3-bucket
            type: terraform.Module
            inputVariables:
              bucket_name: '{{bucket_name}}'
              aws_region: '{{aws_region}}'
            workspaceName: multi-{{aws_region}}
            applyDestroyOperation: "true"
            file: !file "artifacts/2.0.1/bucket-1"
          - name: s3-bucket-backup
            type: terraform.Module
            inputVariables:
              bucket_name: '{{bucket_name}}'
              aws_region: '{{aws_region}}'
            workspaceName: multi-{{aws_region}}
            applyDestroyOperation: "true"
            file: !file "artifacts/2.0.1/bucket-2"
      - name: 3.0.4
        type: udm.DeploymentPackage
        deployables:
          - name: stack
            type: terraform.ConfigurationSpec
            workspaceName: multi-{{aws_region}}
            applyDestroyOperation: "true"
            embeddedModules:
              - name: s3
                type: terraform.EmbeddedModuleArtifact
                file: !file "artifacts/3.0.4/s3"
            modules:
              - name: s3-bucket
                type: terraform.InstantiatedModuleSpec
                inputVariables:
                  name: '{{bucket_name}}'
                  region: '{{aws_region}}'
                outputVariables:
                  my_main_domain_name: 'bucket_domain_name'
                  my_main_id: 'bucket_id'
                source: s3
              - name: s3-bucket-backup
                type: terraform.InstantiatedModuleSpec
                source: s3
                inputVariables:
                  name: '{{bucket_name}}-backup'
                  region: '{{aws_region}}'
                outputVariables:
                  bucket_name_backup_id: 'bucket_id'
      - name: 3.0.3
        type: udm.DeploymentPackage
        deployables:
          - name: stack
            type: terraform.ConfigurationSpec
            workspaceName: multi-{{aws_region}}
            applyDestroyOperation: "true"
            embeddedModules:
              - name: s3
                type: terraform.EmbeddedModuleArtifact
                file: !file "artifacts/3.0.3/s3"
            modules:
              - name: s3-bucket
                type: terraform.InstantiatedModuleSpec
                inputVariables:
                  name: '{{bucket_name}}'
                  region: '{{aws_region}}'
                outputVariables:
                  my_main_domain_name: 'bucket_domain_name'
                  my_main_id: 'bucket_id'
                source: s3
      - name: 3.0.5
        type: udm.DeploymentPackage
        deployables:
          - name: stack
            type: terraform.ConfigurationSpec
            workspaceName: multi-{{aws_region}}
            applyDestroyOperation: "true"
            embeddedModules:
              - name: s3
                type: terraform.EmbeddedModuleArtifact
                file: !file "artifacts/3.0.5/s3"
            modules:
              - name: s3-bucket
                type: terraform.InstantiatedModuleSpec
                inputVariables:
                  name: '{{bucket_name}}'
                  region: '{{aws_region}}'
                inputHCLVariables:
                  tags: '{{tags}}'
                outputVariables:
                  my_main_domain_name: 'bucket_domain_name'
                  my_main_id: 'bucket_id'
                source: s3
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: Applications/multi/3.0.6
    type: udm.DeploymentPackage
    deployables:
      - name: stack
        type: terraform.ConfigurationSpec
        workspaceName: multi-{{aws_region}}
        applyDestroyOperation: "true"
        modules:
          - name: s3-bucket
            type: terraform.InstantiatedModuleSpec
            source: s3
            inputVariables:
              name: '{{bucket_name}}'
              region: '{{aws_region}}'
            outputVariables:
              my_main_domain_name: bucket_domain_name
              my_main_id: bucket_id
            mapInputVariables:
              - name: block__2
                type: terraform.MapInputVariableSpec
                variables:
                  size: 500Mo
                  fs: FAT32
              - name: block__1
                type: terraform.MapInputVariableSpec
                variables:
                  size: 2G
                  fs: NTFS
              - name: tags
                type: terraform.MapInputVariableSpec
                variables:
                  app: petportal
                  version: 12.1.2
        embeddedModules:
          - name: s3
            type: terraform.EmbeddedModuleArtifact
            file: !file "artifacts/3.0.6/s3"
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: Applications/multi/3.0.7
    type: udm.DeploymentPackage
    deployables:
      - name: stack
        type: terraform.ConfigurationSpec
        workspaceName: multi-{{aws_region}}
        applyDestroyOperation: "true"
        modules:
          - name: module2
            type: terraform.InstantiatedModuleSpec
            source: s3
            inputVariables:
              region: '##module1'
            inputHCLVariables:
              connect_string: '##module1'
            outputVariables:
              my_main_domain_name: bucket_domain_name
              my_main_id: bucket_id
          - name: module1
            type: terraform.InstantiatedModuleSpec
            source: s3
            inputVariables:
              name: '{{bucket_name}}'
              region: '{{aws_region}}'
            outputVariables:
              connect_string: connect_string
              region: region
