---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/s3-content
  type: udm.Application  
  children:
  - name: 1.0.0
    type: udm.DeploymentPackage
    deployables:
    - name: content
      type: aws.s3.Folder      
      acl: public-read      
      file: !file "artifacts/1.0.0/files"
  - name: 1.0.1
    type: udm.DeploymentPackage
    deployables:
    - name: content
      type: aws.s3.Folder      
      acl: public-read      
      file: !file "artifacts/1.0.1/files"
