---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/azure-vm
  type: udm.Application
  children:
  - name: 1.0.2
    type: udm.DeploymentPackage
    deployables:
    - name: azure-vm
      type: terraform.Module
      file: !file "artifacts/Applications/azure-vm/1.0.2/azure-vm/azurevm.zip"
