---
apiVersion: xl-deploy/v1
kind: Environments
spec:
  - name: Environments/dev.gcp
    type: udm.Environment
    members:
      - Infrastructure/myOrganization
      - Infrastructure/myOrganization/myOtherWorkspace/myGCPProject
  - name: Environments/dev.aws
    type: udm.Environment
    members:
      - Infrastructure/myOrganization
      - Infrastructure/myOrganization/myWorkspace/aws
    dictionaries:
      - Environments/dev.conf
      - Environments/ec2-dictionary
  - name: Environments/dev.conf
    type: udm.Dictionary
    entries:
      aws_region: eu-west-3
      env: dev
      instance_type: t2.micro
      ami_id: ami-087855b6c8b59a9e4
      bucket_name: benoit.moussaud.bucket
      tags: '{"app":"demo","version":"2.2.1"}'
  - name: Environments/ec2-dictionary
    type: udm.Dictionary
  - name: Environments/dev.az
    type: udm.Environment
    members:
      - Infrastructure/myOrganization
      - Infrastructure/myOrganization/myWorkspace/azure-xl
    dictionaries:
      - Environments/dev.conf
