---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/myOrganization
  type: terraformEnterprise.Organization
  organizationName: xebialabs-france
  url: https://app.terraform.io
  token: !value "tfe_token"   
  deleteWorkspace: true
  children:
  - name: AWSProvider
    type: terraformEnterprise.Provider
    credentials:      
      AWS_SECRET_ACCESS_KEY: !value "aws_secret_access_key"
      AWS_ACCESS_KEY_ID: !value "aws_access_key_id"
  - name: aws
    type: terraformEnterprise.AWSProvider
    credentials:     
    accesskey: !value "aws_secret_access_key"
    accessSecret: !value "aws_access_key_id"
---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/myOrganization/azure-xl
  type: terraformEnterprise.AzureProvider
  subscriptionId: xxxx-xxx-yyy2-zzz-zzrrzrz
  tenantId: xxxx-xxx-yyy2-zzz-zzrrzrz
  clientId: xxxx-xxx-yyy2-zzz-zzrrzrz
  clientKey: aaaaaaa
