---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - name: Infrastructure/localhost
    type: overthere.LocalHost
    os: UNIX
---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/myOrganization
  type: terraformEnterprise.Organization
  organizationName: xebialabs-france
  url: https://app.terraform.io
  token: !value "tfe_token"
  host: ~Infrastructure/localhost
  children:
  - name: myOtherWorkspace
    type: terraformEnterprise.Workspace
    workspaceName: Benoit-975
    terraformVersion: 0.12.24
    children:
    - name: myGCPProject
      type: terraformEnterprise.GcpProvider
      project: mySecretProject
      region: ouest
      zone: 1
      jsonKeyFile: "{}"
  - name: myWorkspace
    type: terraformEnterprise.Workspace
    workspaceName: Benoit-975
    terraformVersion: 0.12.24
    children:
    - name: AWSProvider
      type: terraformEnterprise.Provider
      credentials:
        AWS_SECRET_ACCESS_KEY: !value "aws_secret_access_key"
        AWS_ACCESS_KEY_ID: !value "aws_access_key_id"
    - name: aws
      type: terraformEnterprise.AwsProvider
      credentials:
      accessSecret: !value "aws_secret_access_key"
      accessKey: !value "aws_access_key_id"
      defaultRegion: "eu-west-3"
      additionalMappers:
        aws_s3_mapper: xldtfe.mapper.aws_s3_mapper.AWSS3Mapper
        aws_ec2_mapper: samplemapper.aws_ec2_mapper.AWSEC2Mapper
    - name: azure-xl
      type: terraformEnterprise.AzureProvider
      subscriptionId: !value "subscriptionId"
      tenantId: !value "tenantId"
      clientId: !value "clientId"
      clientKey: !value "clientKey"


